export interface Model {
    identifier: string;
    min_max_length_dots: [number, number];
    min_max_feed: [number, number];
    number_bytes_per_row: number;
    additional_offset_r: number;
    mode_setting: boolean;
    cutting: boolean;
    expanded_mode: boolean;
    compression_support: boolean;
    two_color: boolean;
    num_invalidate_bytes: number;
    series_code: number;
    model_code: number;
    product_id: number;
}

export const ALL_MODELS: Model[] = [
    {
        identifier: "QL-500",
        min_max_length_dots: [295, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: false,
        mode_setting: false,
        expanded_mode: false,
        cutting: false,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x4f,
        product_id: 0x2015,
    },
    {
        identifier: "QL-550",
        min_max_length_dots: [295, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: false,
        mode_setting: false,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x4f,
        product_id: 0x2016,
    },
    {
        identifier: "QL-560",
        min_max_length_dots: [295, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: false,
        mode_setting: false,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x31,
        product_id: 0x2027,
    },
    {
        identifier: "QL-570",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: false,
        mode_setting: false,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x32,
        product_id: 0x2028,
    },
    {
        identifier: "QL-580N",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x33,
        product_id: 0x2029,
    },
    {
        identifier: "QL-600",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x47,
        product_id: 0x20c0,
    },
    {
        identifier: "QL-650TD",
        min_max_length_dots: [295, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x51,
        product_id: 0x201b,
    },
    {
        identifier: "QL-700",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: false,
        mode_setting: false,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x35,
        product_id: 0x2042,
    },
    {
        identifier: "QL-710W",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x36,
        product_id: 0x2043,
    },
    {
        identifier: "QL-720NW",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x37,
        product_id: 0x2044,
    },
    {
        identifier: "QL-800",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: false,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: true,
        num_invalidate_bytes: 400,
        series_code: 0x34,
        model_code: 0x38,
        product_id: 0x209b,
    },
    {
        identifier: "QL-810W",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: true,
        num_invalidate_bytes: 400,
        series_code: 0x34,
        model_code: 0x39,
        product_id: 0x209c,
    },
    {
        identifier: "QL-820NWB",
        min_max_length_dots: [150, 11811],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 90,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: true,
        num_invalidate_bytes: 400,
        series_code: 0x34,
        model_code: 0x41,
        product_id: 0x209d,
    },
    {
        identifier: "QL-1050",
        min_max_length_dots: [295, 35433],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 162,
        additional_offset_r: 44,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x50,
        product_id: 0x2020,
    },
    {
        identifier: "QL-1060N",
        min_max_length_dots: [295, 35433],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 162,
        additional_offset_r: 44,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x34,
        product_id: 0x202a,
    },
    {
        identifier: "QL-1100",
        min_max_length_dots: [301, 35434],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 162,
        additional_offset_r: 44,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x43,
        product_id: 0x20a7,
    },
    {
        identifier: "QL-1110NWB",
        min_max_length_dots: [301, 35434],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 162,
        additional_offset_r: 44,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x44,
        product_id: 0x20a8,
    },
    {
        identifier: "QL-1115NWB",
        min_max_length_dots: [301, 35434],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 162,
        additional_offset_r: 44,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x34,
        model_code: 0x45,
        product_id: 0x20ab,
    },
    {
        identifier: "PT-E550W",
        min_max_length_dots: [31, 14172],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 16,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x68,
        product_id: 0x2060,
    },
    {
        identifier: "PT-P700",
        min_max_length_dots: [31, 7086],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 16,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x67,
        product_id: 0x2061,
    },
    {
        identifier: "PT-P750W",
        min_max_length_dots: [31, 7086],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 16,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x68,
        product_id: 0x2062,
    },
    {
        identifier: "PT-P900W",
        min_max_length_dots: [57, 28346],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 70,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x69,
        product_id: 0x2085,
    },
    {
        identifier: "PT-P950NW",
        min_max_length_dots: [57, 28346],
        min_max_feed: [35, 1500],
        number_bytes_per_row: 70,
        additional_offset_r: 0,
        compression_support: true,
        mode_setting: true,
        expanded_mode: true,
        cutting: true,
        two_color: false,
        num_invalidate_bytes: 200,
        series_code: 0x30,
        model_code: 0x70,
        product_id: 0x2086,
    },
];
